<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKaPv0Eo\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKaPv0Eo/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKaPv0Eo.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKaPv0Eo\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKaPv0Eo\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KaPv0Eo',
    'container.build_id' => '8a69ae9c',
    'container.build_time' => 1517416886,
));
