<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUi43c93\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUi43c93/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUi43c93.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUi43c93\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUi43c93\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ui43c93',
    'container.build_id' => '46d0b8b4',
    'container.build_time' => 1517426448,
));
